<?php

function myeventlane_boost_preprocess_html(&$variables) {
  \Drupal::logger('boost_debug')->notice('THEME FILE IS LOADED!');
}

function myeventlane_boost_preprocess_boost_event_page(&$variables) {
  \Drupal::logger('boost_debug')->notice('PREPROCESS for boost_event_page called.');
}

/**
 * Implements hook_theme().
 */
function myeventlane_boost_theme($existing, $type, $theme, $path) {
  return [
    'boost_event_page' => [
      'variables' => [
        'event' => NULL,
        'message' => NULL,
        'purchase_form' => NULL,
      ],
      'template' => 'boost-event-page', // This matches boost-event-page.html.twig
    ],
  ];
}

