<?php

use Drupal\Core\Theme\ThemeManagerInterface;

/**
 * Implements hook_theme().
 */
function myeventlane_user_theme($existing, $type, $theme, $path) {
  return [
    'my_events_dashboard' => [
      'variables' => [
        'rsvps' => NULL,
        'orders' => NULL,
      ],
      'template' => 'my-events',
    ],
    'my_profile_page' => [
          'variables' => [
            'user' => NULL,
            'is_vendor' => FALSE,
            'rsvps' => [],
            'orders' => [],
          ],
          'template' => 'my-profile',
        ],
  ];
}

/**
 * Preprocess variables for my_profile_page theme hook.
 */
function myeventlane_user_preprocess_my_profile_page(array &$variables): void {
  $theme = \Drupal::service('theme.manager')->getActiveTheme();
  $variables['directory'] = $theme->getPath();
}
