layout_builder_styles.style.*.third_party.lb_styles_conditions:
  type: sequence
  label: 'Layout Builder Styles Conditions settings'
  sequence:
    type: condition.plugin.[%key]
    label: 'Context condition'

lb_styles_conditions.settings:
  type: config_object
  label: 'Layout Builder Styles Conditions settings'
  mapping:
    enabled_conditions:
      type: sequence
      label: 'Enabled conditions'
      sequence:
        type: string
        label: 'Condition plugin ID'
