<?php

/**
 * Implements hook_theme().
 */
function myeventlane_profile_theme($existing, $type, $theme, $path) {
  $module_path = \Drupal::service('extension.path.resolver')->getPath('module', 'myeventlane_profile');

  return [
    'myeventlane_profile' => [
      'variables' => ['title' => NULL, 'content' => NULL],
      'template' => 'myeventlane-profile',
      'path' => $module_path . '/templates',
    ],
    'myeventlane_rsvp_cards' => [
      'variables' => [
        'title' => NULL,
        'items' => [], // array of normalized RSVP card items
      ],
      'template' => 'myeventlane-rsvp-cards',
      'path' => $module_path . '/templates',
    ],
  ];
}
